package edu.andrews.cptr475.bernardm.andrewsapp.RssNewFeed.PARSERTESTING;

import android.net.Uri;
import android.util.Log;

import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserException;
import org.xmlpull.v1.XmlPullParserFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;

/**
 * Created by drmaq on 4/7/15.
 */
public class RSSPARSER {
    /** Log message tag */
   public static final String TAG = " ";
    /** URL for flickr API */
    private static final String ENDPOINT = "https://www.andrews.edu/agenda/category/Campus+News/limit/15/rss";
    /** Required Key used to access flickr API (generated by Yahoo)*/
    //private static final String API_KEY = "2b5618206f6e0323db446e3a35d9efb9";
    /** flickr API method for requesting recent images */
    private static final String METHOD_GET_RECENT = " ";
   /** code for extra parameter */
    private static final String PARAM_EXTRAS = "extra";
    /** parameter value for requesting small version of image (if available) */
    private static final String EXTRA_SMALL_URL = "url_s";
    /** name of photo tag in XML for the image information */
   private static final String XML_PHOTO = "photo";

    /**
     * Request image from Flickr.
     * @return list of gallery items(images) download from flickr.
     */
    public ArrayList<StoreItem> fetchItems(){
        ArrayList<StoreItem> items = new ArrayList<StoreItem>();
        try{
            String url = Uri.parse(ENDPOINT).buildUpon().appendQueryParameter("method", METHOD_GET_RECENT).appendQueryParameter("api_key",API_KEY).appendQueryParameter(PARAM_EXTRAS, EXTRA_SMALL_URL).build().toString();
            //Submit query to flickr and download resulting information
            String xmlString = getUrl(url);
            Log.i(TAG, "Received xml: \n" + xmlString);
            //Create an instance of the xml parser
            XmlPullParserFactory factory = XmlPullParserFactory.newInstance();
            XmlPullParser parser = factory.newPullParser();
            parser.setInput(new StringReader(xmlString));

            //parse the xml photo elements
            //and create gallery items for each one
            parseItems(items, parser);
        } catch (IOException ioe){
            Log.e(TAG, "Failed to fetch items",ioe);
        } catch (XmlPullParserException xppe){
            Log.e(TAG, "Failed to parse items", xppe);
        }
        return items;
    }
    /**
     * PArse Photo elements in an XML string one-by-one
     * @param items List of GalleryItems to add to.
     *              Each photo elements result in a new StoreItem
     *              that is added to the list
     * @param parser XML parser object initialized with string to parse
     * @throws org.xmlpull.v1.XmlPullParserException
     * @throws java.io.IOException
     */
    void parseItems(ArrayList<StoreItem> items, XmlPullParser parser) throws XmlPullParserException, IOException{
        int eventType = parser.next();
        // Keep parsing photo elements and converting them to Gallery items until we reach the end of the XML string.
        while (eventType != XmlPullParser.END_DOCUMENT){
            if (eventType == XmlPullParser.START_TAG && XML_PHOTO.equals(parser.getName())){
                //Extract image Id
                String item = parser.getAttributeValue(null, "item");
                //Extract image Title
                String title = parser.getAttributeValue(null, "title");
                //Extract url for image Thumbnail
                String description = parser.getAttributeValue(null, "description");

                //Create new Gallery item for image
                StoreItem item = new StoreItem();
                item.setTitle(title);
                item.setDescription(description);
                //item.setUrl(smallURL);
                items.add(item);
            }
            //move to next xml element in the file.
            eventType = parser.next();
        }
    }
    /**
     * Retrieve raw data from a given URL and return it as an array of bytes.
     * @param urlSpec String specifying the URL to access.
     * @return Array of bytes from given URL
     * @throws IOException
     */
    public byte[] getUrlBytes(String urlSpec) throws IOException {
        URL url = new URL(urlSpec);
        // Setup a connection object, but don't connect until getInputStrearm called
        HttpURLConnection connection = (HttpURLConnection)url.openConnection();

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            // Establish a connection
            InputStream in = connection.getInputStream();

            if (connection.getResponseCode() != HttpURLConnection.HTTP_OK) {
                return null;
            }

            // read 1K of bytes from input stream until nothing left to read.
            // write each set of bytes to the output byte array
            int bytesRead = 0;
            byte[] buffer = new byte[1024];
            while ((bytesRead = in.read(buffer))> 0) {
                out.write(buffer, 0, bytesRead);
            }
            out.close();
            return out.toByteArray();
        } finally {
            connection.disconnect();
        }
    }

    /**
     * Retrieve raw data from a given URL and return it as a String.
     * @param urlSpec String specifying the URL to access.
     * @return String from given URL
     * @throws IOException
     */
    String getUrl(String urlSpec) throws IOException {
        return new String(getUrlBytes(urlSpec));
    }


}
